// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB81c_unAOf8dysmfPApEIQsj5K3iutAMM',
    appId: '1:651555326754:web:b70015ffa0680d30e9737b',
    messagingSenderId: '651555326754',
    projectId: 'chat-app-4fb15',
    authDomain: 'chat-app-4fb15.firebaseapp.com',
    storageBucket: 'chat-app-4fb15.appspot.com',
    measurementId: 'G-H9GJ89MQKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-uqh9h27yBGKEzwzoJYR40CFXsWlMgk',
    appId: '1:651555326754:android:ba52f6a7fb30cfade9737b',
    messagingSenderId: '651555326754',
    projectId: 'chat-app-4fb15',
    storageBucket: 'chat-app-4fb15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA6P5DhS571AteuPozWMIOKx3zRlALLo8',
    appId: '1:651555326754:ios:432d7f8abf002bc0e9737b',
    messagingSenderId: '651555326754',
    projectId: 'chat-app-4fb15',
    storageBucket: 'chat-app-4fb15.appspot.com',
    iosClientId: '651555326754-ll4uls1v292ejd78cu7db3227oqd8pdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
